# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-01 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20170131_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(),
        ),
    ]
