# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-16 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_auto_20170208_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
